container:
  image: node:10

lint_task:
  install_script: npm install
  test_script: npm run lint

test_task:
  container:
    matrix:
      image: node:11
      image: node:10
  install_script: npm install
  test_script: npm test

commit_lint_task:
  script:
    - npm install
    - npm run commitlint

coverage_task:
  env:
    CODECOV_TOKEN: ENCRYPTED[5897f1a68e8ddffa02bf3e5ff22acf0ee790b4fd83461df4043ae30f75df44142afe3ae0f99b33bcc25165f9de7fd79f]
  script:
    - npm install
    - npm test
    - npm run codecov

publish_task:
  only_if: $CIRRUS_BRANCH == 'master'
  depends_on:
    - test_task
    - lint_task
    - commit_lint_task
  environment:
    GITHUB_TOKEN: ENCRYPTED[492a9fea322d8f4acd84399a439ca7f44130dc7fedef820ea444e78f3043009eba06d323e8a0a0bef07f177a36fece05]
    NPM_TOKEN: ENCRYPTED[16e3a59d4c2aa6318f02ac657c530b0b26cca1a571105c43a2af067cd293d918ed32708c64d195ac0d1e24f837d8c55f]
  script:
    - npm install
    - npm run compile
    - npx semantic-release
