on:
  push:
    branches:
      - main
name: release
jobs:
  release-please:
    if: github.repository == 'JustinBeckwith/promotime'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    if: needs.release-please.outputs.release_created
    runs-on: ubuntu-latest
    needs: release-please
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run compile
      - run: npm publish --provenance --access public
